[project]
name = "nutrionisit-agent-agno"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno[aws]>=1.5.3",
    "exa-py>=1.13.1",
    "python-dotenv>=1.1.0",
    "streamlit>=1.45.1",
]
