[project]
name = "yt-post-gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno[aws,ollama]>=1.7.1",
    "anthropic>=0.57.1",
]
